railsapp/testapp/config/routes.rb
Rails.application.routes.draw do

	resources :subjects do
		member do
			get :delete
		end
	end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#get 'display/index'
#get ':controller(/:action(/:id))'
end

railsapp/testapp/app/models/admin_user.rb
class AdminUser < ApplicationRecord

	has_and_belongs_to_many :pages
	has_many :section_edits
	has_many :sections, :through => :section_edits
end

railsapp/testapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

railsapp/testapp/app/models/page.rb
class Page < ApplicationRecord
	
	belongs_to :subject
	has_and_belongs_to_many :user_names
	has_many :sections
end

railsapp/testapp/app/models/section.rb
class Section < ApplicationRecord
belongs_to :page
has_many :section_edits
has_many :admin_users, :through => :section_edits
end

railsapp/testapp/app/models/section_edit.rb
class SectionEdit < ApplicationRecord

	belongs_to :user_name
	belongs_to :section
end

railsapp/testapp/app/models/subject.rb
class Subject < ApplicationRecord

	has_many :pages
end

railsapp/testapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

railsapp/testapp/app/controllers/display_controller.rb
class DisplayController < ApplicationController


	def index	
		render('index')
	end

	def show
		@array = [1,2,3,4,5,6]
		@id = params['id']
		@page = params['page']
		render('show')
	end

	def other_show
		redirect_to(:action => 'index')
	end
end

railsapp/testapp/app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
	@subjects = Subject.all
  end

  def show
	@subject = Subject.find(params[:id])
  end

  def new
	@subject = Subject.new
  end
  
  def create
  end

  def edit
  end
  
  def update
  end

  def delete
  end
  
  def destroy
  end

end

railsapp/testapp/app/helpers/application_helper.rb
module ApplicationHelper
end

railsapp/testapp/app/helpers/display_helper.rb
module DisplayHelper
end

railsapp/testapp/app/helpers/subjects_helper.rb
module SubjectsHelper
end

railsapp/testapp/app/views/display/index.html.erb
<h1>Hello , Welcome to My Site </h1>
<%= link_to("This will take you to Second page", {:action => 'show', :page => 5, :id => 1}) %>

railsapp/testapp/app/views/display/show.html.erb
<h1>this is coming from show action</h1>
<% @array.each do |x| %>
	<h1><%= x %></h1>
	<% end %>
	<h2>Click below link to go back to index page</h2><br>
	<%= link_to("This will take you to index page", {:action => 'index'}) %>

	<%= link_to("This will take you to Second page", {:action => 'index', :page => 5, :id => 1}) %>

	<br>
	ID : <%= @id %> <br>
	Page: <%= @page %>

railsapp/testapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

railsapp/testapp/app/views/subjects/delete.html.erb
<h1>Subjects#delete</h1>
<p>Find me in app/views/subjects/delete.html.erb</p>

railsapp/testapp/app/views/subjects/edit.html.erb
<h1>Subjects#edit</h1>
<p>Find me in app/views/subjects/edit.html.erb</p>

railsapp/testapp/app/views/subjects/index.html.erb
<div class="subjects index">
	<h2>Subjects</h2>
	<%= link_to("Add New Subject", 'new_subject', :class => 'action new') %>
	<table class="listing" summary="Subject List">
		<tr class="header">
			<th>Subject</th>
			<th>Visible</th>
			<th>Pages</th>
			<th>Action</th>
		</tr>
		<% @subjects.each do |subject| %>
		<tr>
			<td><%= subject.position %></td>
			<td><%= subject.name %></td>
			<td class="center"><%= subject.visible ? 'yes' : 'no' %></td>
			<td class="center"><%= subject.pages.size %></td>
			<td class="action">
				<%= link_to("Show", 'subject_path(subject.id)', :class => 'action show') %>
				<%= link_to("Edit", '#', :class => 'action edit') %>
				<%= link_to("Delete", '#', :class => 'action delete') %>
			</td>
		</tr>
		<% end %>
	</table>


</div>

railsapp/testapp/app/views/subjects/new.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects new">
<h2>Create Subjects</h2>

<%= form_for(@subject) do |f| %>
<table summary="subject form fields">
<tr>
  <th>Name</th>
  <td><%= f.text_field(:name) %></td>
</tr>
<tr>
  <th>Position</th>
  <td><%= f.text_field(:position) %></td>
</tr>
<tr>
  <th>Visible</th>
  <td><%= f.text_field(:visible) %></td>
</tr>
</table>

<div class="form-buttons">
<%= f.submit("Create Subject") %>
</div>
<% end %>
</div>

railsapp/testapp/app/views/subjects/show.html.erb
<%= link_to("<< Back to list", subjects_path, :class => 'back-link') %>

<div class="subjects show">
<h2>Show Subject</h2>

<table summary="Subject detail view">
	<tr>
		<th>Name</th>
		<td><%= @subject.name %></td>
	</tr>
	 <tr>
                <th>Position</th>
                <td><%= @subject.position %></td>
        </tr>
	 <tr>
                <th>Visible?</th>
                <td><%= @subject.visible ? 'true' : 'false' %></td>
        </tr>

	 <tr>
                <th>Created</th>
                <td><%= @subject.created_at %></td>
        </tr>

	 <tr>
                <th>Updated</th>
                <td><%= @subject.updated_at %></td>
        </tr>
</table>
</div>